#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/figlet
  pkg ensure sysutils/pv
  pkg ensure x11/xtermset || true
}

bootstrap
